### ISSUE TITLE
File path error in writer

### ISSUE THREAD

**Issue by thvitt** [DARIAH-DE/DARIAH-DKPro-Wrapper#24]
```
2016-07-07T20:35:24,625	ERROR	de.tudarmstadt.ukp.dariah.pipeline.RunPipeline	Processing failed for file: grenzboten\1922__Macht_27.txt, Message: null, Cause: Base URI [file:C:\daten\grenzboten/] is not a prefix of document URI [file:C:\daten\grenzboten\1922__Macht_27.txt]
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.tudarmstadt.ukp.dariah.IO.DARIAHWriter.process(DARIAHWriter.java:126) ~[ddw-0.4.5.jar:?]
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[ddw-0.4.5.jar:?]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385) ~[ddw-0.4.5.jar:?]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308) ~[ddw-0.4.5.jar:?]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570) ~[ddw-0.4.5.jar:?]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412) ~[ddw-0.4.5.jar:?]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344) ~[ddw-0.4.5.jar:?]
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265) ~[ddw-0.4.5.jar:?]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269) ~[ddw-0.4.5.jar:?]
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:150) ~[ddw-0.4.5.jar:?]
	at de.tudarmstadt.ukp.dariah.pipeline.RunPipeline.main(RunPipeline.java:611) [ddw-0.4.5.jar:?]
Caused by: java.lang.IllegalStateException: Base URI [file:C:\daten\grenzboten/] is not a prefix of document URI [file:C:\daten\grenzboten\1922__Macht_27.txt]
	at de.tudarmstadt.ukp.dkpro.core.api.io.JCasFileWriter_ImplBase.getRelativePath(JCasFileWriter_ImplBase.java:246) ~[ddw-0.4.5.jar:?]
	at de.tudarmstadt.ukp.dkpro.core.api.io.JCasFileWriter_ImplBase.getOutputStream(JCasFileWriter_ImplBase.java:149) ~[ddw-0.4.5.jar:?]
	at de.tudarmstadt.ukp.dariah.IO.DARIAHWriter.process(DARIAHWriter.java:122) ~[ddw-0.4.5.jar:?]
	... 10 more
2016-07-07T20:35:24,662	INFO	de.tudarmstadt.ukp.dariah.IO.TextReaderWithInfo	Process file: 1922_Zweikampf_oder_Mord_78.txt
```
berichtet von @fotis007

mit 0.44 habe es funktioniert (aber ich hab damit nix gemacht mit dem writer?)

**Comment by thvitt** [comment]
0.44 did not yet contain [this modification](https://github.com/dkpro/dkpro-core/commit/002d1cd7#diff-9399aa8ff996381bf8b1504edeb90581R124) to DKPro core which actually uses the fact that the documentURI and baseURI annotations should be valid URIs.
